name: ✨ update awesome-stars
on:
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * *
jobs:
  awesome-stars:
    name: 💾 update awesome-stars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: 💂 Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 📥 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install starred
      - name: 💾 update repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: starred --username ju-c --repository stars --sort --token ${GITHUB_TOKEN} --message 'stars update by github actions cron'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: stars update by github actions cron
          commit_user_name: ju-c
          commit_user_email: ${{secrets.EMAIL_ADDRESS}}
          commit_author: ju-c <${{secrets.EMAIL_ADDRESS}}>


